services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # react
  app:
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/node_modules:/app/node_modules
#    extra_hosts:
#      # Ensure that host.docker.internal is correctly defined on Linux
#      - host.docker.internal:host-gateway
  visualize:
    build:
        dockerfile: ./visualize/Dockerfile
    ports:
      - "5184:5184"
      - "9000:9000"
      - "8050:8050"
    volumes:
      - ./visualize/node_modules:/app/node_modules
  flask:
    build:
      dockerfile: ./flask/Dockerfile
    volumes:
      - ./flask:/app
#  npm:
#    build:
#      dockerfile: ./node/Dockerfile
#    volumes:
#      - "./app/node_modules:/app/node_modules"
#volumes:
#  mysqldata: