services:
  # nginx
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # react
  app:
    build:
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
#      - ./app/node_modules:/usr/src/app/node_modules
      - "./app/src:/usr/src/app/src:delegated"
  # visualiser
  visualize:
    build:
        dockerfile: ./visualize/Dockerfile
    ports:
      - "5184:5184"
      - "9000:9000"
      - "8050:8050"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
#      - ./visualize/node_modules:/usr/src/app/node_modules
      - ./visualize/src:/usr/src/app/src
  # model prediction
  flask:
    build:
      dockerfile: ./flask/Dockerfile
    volumes:
      - ./flask:/app
