services:
  tfserve:
    image: tensorflow/serving:latest-gpu
    restart: unless-stopped
    ports:
      - "8501:8501"
    gpus: "all"
    volumes:
      - ./models:/models
    command: --model_config_file=/models/models.config
volumes:
    models:
